# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.0.0
    hooks:
    -   id: commitizen
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: detect-private-key
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
    -   id: terraform_fmt
        args:
            - --args=-check
            - --args=-diff
    -   id: terragrunt_fmt
        args:
            - --args=-terragrunt-exclude-dir=*/.terragrunt-cache/*
            - --args=-terragrunt-check
            - --args=-terragrunt-diff
    -   id: terraform_tflint
    -   id: terraform_validate
        args:
            - --hook-config=--retry-once-with-cleanup=true
    -   id: terraform_trivy # static analysis of security settings in your Terraform code
        args:
            - --args=--skip-dirs="**/.terraform"
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
    -   id: gitleaks
