# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket = "github-tf-state-bucket"
    prefix = "terraform/github-foundations/organizations/projects/github_foundations/FociSolutions/repositories"
  }
}
