# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa


provider "google" {
}

data "google_secret_manager_secret_version_access" "pem_file" {
  project = "prj-g-github-foundations57449"
  secret = "FociSolutionsPem"
}

data "google_secret_manager_secret" "pem_file_metadata" {
  project = "prj-g-github-foundations57449"
  secret_id = "FociSolutionsPem"
}

provider "github" {
    owner = "FociSolutions"
    app_auth {
      id              = data.google_secret_manager_secret.pem_file_metadata.annotations.appId        
      installation_id = data.google_secret_manager_secret.pem_file_metadata.annotations.installationId 
      pem_file        = data.google_secret_manager_secret_version_access.pem_file.secret_data
    }
    }
