name: "Confirm Resource Deletion"

on:
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

env:
  tf_version: 1.7.5
  tg_version: 0.55.18
  working_dir: .

jobs:
    confirm-deletion:
        permissions:
            contents: 'read'
            id-token: 'write'
            pull-requests: 'write'
            issues: 'write'
        name: "Confirm the Deletion"
        runs-on: ubuntu-latest
        steps:
        - name: Confirm Deletion
          uses: actions/github-script@v7
          # Run the deletion confirmation, only when a *new*
          # comment is added to a PR or a review is submitted
          if: |
            (github.event.action == 'submitted' &&
             github.event.review.body == 'delete') ||
            (github.event.action == 'created' &&
             github.event.comment.body == 'delete' &&
             github.event.issue.pull_request)
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            # runs only if there is a 'request changes' review,
            # created by the Github Actions bot, with a status of
            # 'outstanding'
            script: |
                // First we check if the pull request has a 'request changes' review
                const reviews = await github.rest.pulls.listReviews({
                    pull_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo
                });

                // Filter the reviews to find the one created by the Github Actions bot
                change_reviews = reviews?.data?.filter(
                    review => review.state == 'CHANGES_REQUESTED'
                    && review.user.login?.startsWith('github-actions')
                );

                console.log(`Found reviews: ${JSON.stringify(change_reviews)}\n\n`);

                if (change_reviews) {
                    // iterate each pending review and dismiss it
                    for (const review of change_reviews) {
                        console.log(`Updating the review with id ${review.id}`)
                        const result = await github.rest.pulls.dismissReview({
                            pull_number: context.issue.number,
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            review_id: review.id,
                            message: 'Deletion confirmed. Ready to merge.'
                        });
                        console.log(`Updated the review with id ${review.id}.`)

                    }
                } else {
                    console.log('No valid review found');
                }
