#!/bin/sh

# Regex to validate commit message format
commit_regex='^(add|build|chore|ci|docs|feat|fix|perf|refactor|remove|revert|style|test)(\(.+\))?: .+'

# ANSI escape code for red
red='\033[0;31m'

# ANSI escape code for blue
blue='\033[0;34m'

# ANSI escape code for yellow
yellow='\033[0;33m'

# ANSI escape code to bold
bold='\033[1m'

# ANSI escape code to reset color
no_color='\033[0m'


if ! head -1 "$1" | grep -qE "$commit_regex"; then
  echo "" >&2
  echo "${red}${bold}ERROR${no_color}${red}: Your commit message does not conform to the Conventional Commits format.${no_color}" >&2
  echo "" >&2
  echo "\t${bold}<type>(optional scope): <description>${no_color}" >&2
  echo "\t<body>(optional: a longer description of the change)" >&2
  echo "\t<footer>(optional: a closing line with a reference issue or breaking change)" >&2
  echo "" >&2
  echo "${yellow}Example:${no_color}" >&2
  echo "\t> \"fix(docs): correct typo\"" >&2
  echo "\t> \"feat: add new feature" >&2
  echo "\t   The new shiny widget is now available to all users" >&2
  echo "\t   BREAKING CHANGE: the old widget is no longer available\"" >&2
  echo "" >&2
  echo "For more details, see ${blue}https://www.conventionalcommits.org${no_color}" >&2
  echo "" >&2
  exit 1
fi
