// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockImportIdResolver is an autogenerated mock type for the ImportIdResolver type
type MockImportIdResolver struct {
	mock.Mock
}

type MockImportIdResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImportIdResolver) EXPECT() *MockImportIdResolver_Expecter {
	return &MockImportIdResolver_Expecter{mock: &_m.Mock}
}

// ResolveImportId provides a mock function with given fields: resourceAddress
func (_m *MockImportIdResolver) ResolveImportId(resourceAddress string) (string, error) {
	ret := _m.Called(resourceAddress)

	if len(ret) == 0 {
		panic("no return value specified for ResolveImportId")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(resourceAddress)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(resourceAddress)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(resourceAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImportIdResolver_ResolveImportId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveImportId'
type MockImportIdResolver_ResolveImportId_Call struct {
	*mock.Call
}

// ResolveImportId is a helper method to define mock.On call
//   - resourceAddress string
func (_e *MockImportIdResolver_Expecter) ResolveImportId(resourceAddress interface{}) *MockImportIdResolver_ResolveImportId_Call {
	return &MockImportIdResolver_ResolveImportId_Call{Call: _e.mock.On("ResolveImportId", resourceAddress)}
}

func (_c *MockImportIdResolver_ResolveImportId_Call) Run(run func(resourceAddress string)) *MockImportIdResolver_ResolveImportId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockImportIdResolver_ResolveImportId_Call) Return(_a0 string, _a1 error) *MockImportIdResolver_ResolveImportId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImportIdResolver_ResolveImportId_Call) RunAndReturn(run func(string) (string, error)) *MockImportIdResolver_ResolveImportId_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImportIdResolver creates a new instance of MockImportIdResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImportIdResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImportIdResolver {
	mock := &MockImportIdResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
